version: "3.9"
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: flask
      POSTGRES_PASSWORD: flask
      POSTGRES_DB: counterdb
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

    web:
      build: .
      restart: always
      ports:
        - "5000:5000"
      depends_on:
        - db
      volumes:
        - .:/app

volumes:
  db_data:
