version: "3.9"
services:
  web:
    build: .
    restart: always
    ports:
      - "8765:5000"
    depends_on:
      - db
    volumes:
      - .:/app

  db:
    image: postgres:13
    container_name: db
    environment:
      POSTGRES_USER: flask
      POSTGRES_PASSWORD: flask
      POSTGRES_DB: counterdb
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: qwe@mail.ru
      PGADMIN_DEFAULT_PASSWORD: qwe
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin

    ports:
      - "5050:80"
    restart: unless-stopped

volumes:
  db_data:
  pgadmin:
